### ISSUE TITLE
MySQL create index error

### ISSUE THREAD

**Issue by moehrlei** [nsip/sif3-framework-java#4]
When I ran the script 'SIF3InfrastructureERM_DDL_mysql.sql' I got the following error:

CREATE INDEX `SEC_TOKEN_IDX` ON `SIF3_SESSION` (`SECURITY_TOKEN` ASC, `ADAPTER_TYPE` ASC)
Error Code: 1071. Specified key was too long; max key length is 767 bytes

I removed the statement and the rest of the script ran fine.

**Comment by joerghuber** [comment]
I have provided a work around for this. It is a commonly known issue with MySQL (http://mechanics.flite.com/blog/2014/07/29/using-innodb-large-prefix-to-avoid-error-1071/). The latest scripts which will now work are on the v0.6.0 branch for the time being.
