### ISSUE TITLE
Compilation failure: unmappable character for encoding UTF8

### ISSUE THREAD

**Issue by lduivenbode** [nsip/sif3-framework-java#5]
**Ubuntu 14.04.3 / Oracle JDK 1.8.0_60**

_SIF3InfraREST/sif3Common/src/sif3/common/interfaces/QueryConsumer.java:69_
```
* @return A list of responses with one response for each zone/context combination. The data in the response is a �collection-type� style
```

_SIF3InfraREST/sif3Common/src/sif3/common/interfaces/QueryConsumer.java:104_
```
* @return A list of responses with one response for each zone/context combination. The data in the response is a �collection-type� style
```

**Comment by joerghuber** [comment]
I believe this is fixed. I cannot see the offending character in my sub-mission.
