### ISSUE TITLE
environment_xml column too small when autogenerating schema

### ISSUE THREAD

**Issue by shlusiak** [nsip/sif3-framework-java#8]
In file SIF3Infra.hbm.xml:

```
<property name="environmentXML" column="ENVIRONMENT_XML" type="string"/>
```

In PostgreSQL this maps to a varchar(255) which is too small for most environment xmls. Changing the type to "text" makes everything awesome.

**Comment by joerghuber** [comment]
This has been fixed in the appropriate hibernate mapping file.
